<?php

// Variables
return [
    'creatorName' => 'Tim Teknis WR4 Bidang DTI',
    'creatorUrl' => 'https://eos.usk.ac.id',
    'templateName' => 'EOS',
    'templateSuffix' => 'Executive Operation System',
    'templateVersion' => '3.0.0',
    'templateFree' => false,
    'templateDescription' => 'Executive Operation System',
    'templateKeyword' => 'Executive Operation System',
    'licenseUrl' => 'https://eos.usk.ac.id',
    'livePreview' => 'https://eos.usk.ac.id',
    'productPage' => 'https://eos.usk.ac.id',
    'support' => 'https://eos.usk.ac.id',
    'moreThemes' => 'https://eos.usk.ac.id',
    'ogTitle' => 'EOS - Executive Operation System',
    'ogImage' => 'https://eos.usk.ac.id',
    'ogType' => 'product',
    'documentation' => 'https://eos.usk.ac.id',
    'generator' => '',
    'changelog' => 'https://eos.usk.ac.id',
    'repository' => 'https://eos.usk.ac.id',
    'gitRepo' => 'eos-usk',
    'gitRepoAccess' => 'https://eos.usk.ac.id',
    'githubFreeUrl' => 'https://eos.usk.ac.id',
    'facebookUrl' => 'https://eos.usk.ac.id',
    'twitterUrl' => 'https://eos.usk.ac.id',
    'githubUrl' => 'https://eos.usk.ac.id',
    'dribbbleUrl' => 'https://eos.usk.ac.id',
    'instagramUrl' => 'https://eos.usk.ac.id',
];
